server:
  port: 8090
  servlet:
    context-path: /api/v1

payment:
  server:
    url: http://payment-service.payment-ns.svc.cluster.local
    prefix: /api/v1/server-admin

user:
  server:
    url: http://user-service.user-ns.svc.cluster.local
    prefix: /api/v1/server-admin

spring:
  application:
    name: admin-service
#  zipkin:
#    base-url: http://zipkin.allback.site:9411
#    enabled: true
#  sleuth:
#    sampler:
#      probability: 1.0
#    enabled: true

## Eureka Client
#eureka:
#  instance:
#    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://eureka-service.eureka-ns.svc.cluster.local:8761/eureka/

springdoc:
  swagger-ui:
    config-url: /admin-service/api/v1/v3/api-docs/swagger-config
    url: /admin-service/api/v1/v3/api-docs
