server:
  port: 8080

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://eureka-service.eureka-ns.svc.cluster.local:8761/eureka/

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: user-service
          uri: http://auth.allback.site
          predicates:
            - Path= /api/v1/oauth2/**, /api/v1/login/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: user-service
          uri: http://user-service.user-ns.svc.cluster.local
          predicates:
            - Path=/user-service/api/v1/swagger-ui/**, /user-service/api/v1/v3/api-docs/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: user-service
          uri: http://user-service.user-ns.svc.cluster.local
#          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: payment-service
          uri: http://payment-service.payment-ns.svc.cluster.local
          predicates:
            - Path=/payment-service/api/v1/swagger-ui/**, /payment-service/api/v1/v3/api-docs/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/payment-service/(?<segment>.*), /$\{segment}

        - id: payment-service
          uri: http://payment-service.payment-ns.svc.cluster.local
#          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/payment-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: concert-service
          uri: http://concert-service.concert-ns.svc.cluster.local
          predicates:
            - Path=/concert-service/api/v1/swagger-ui/**, /concert-service/api/v1/v3/api-docs/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/concert-service/(?<segment>.*), /$\{segment}

        - id: concert-service
          uri: http://concert-service.concert-ns.svc.cluster.local
#          uri: lb://CONCERT-SERVICE
          predicates:
            - Path=/concert-service/**
          filters:
#            - name: KafkaRequestFilter
#              args:
#                topicName: concert-req
            - RemoveRequestHeader=Cookie
            - RewritePath=/concert-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
#            - KafkaRequestFilter

        - id: admin-service
          uri: http://admin-service.admin-ns.svc.cluster.local
          predicates:
            - Path=/admin-service/api/v1/swagger-ui/**, /admin-service/api/v1/v3/api-docs/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/admin-service/(?<segment>.*), /$\{segment}

        - id: admin-service
          uri: http://admin-service.admin-ns.svc.cluster.local
#          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/admin-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

jwt:
  secret: UDVaY0VRREoyaEl2d2JlWXFFN2haOWF3ekRxbFBzTnpscEFFaE5mdDBSZw==

#kafka:
#  bootstrap-servers: 3.34.8.99:9092
#  topic: concert-req
#  partition: 1
